name: nyxx_commander
version: 3.0.0-dev.0
description: Nyxx Commander Module. Discord library for Dart. Simple, robust framework for creating discord bots for Dart language.
homepage: https://github.com/nyxx-discord/nyxx
repository: https://github.com/nyxx-discord/nyxx
documentation: https://nyxx.l7ssha.xyz
issue_tracker: https://github.com/nyxx-discord/nyxx/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  http: ^0.13.3
  logging: ^1.0.1
  nyxx: ^3.0.0-dev.0

dev_dependencies:
  build_runner: ^2.1.4
  coverage: ^1.0.3
  lints: ^1.0.1
  mockito: ^5.0.16
  test: ^1.19.0
